# Linear regression with Ridge model of regularisation 

-использовать линейную регрессию
-применить линейную регрессию к текстовым данным

Задача:  предсказать оклад, исходя из описания вакансии.

In [6]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
X_train = pd.read_csv('salary-train.csv', nrows=10000)

In [8]:
X_train.head(3)

FullDescription LocationNormalized  \
0  International Sales Manager London ****k  ****...             London   
1  An ideal opportunity for an individual that ha...             London   
2  Online Content and Brand Manager// Luxury Reta...  South East London   

  ContractTime  SalaryNormalized  
0    permanent             33000  
1    permanent             50000  
2    permanent             40000

In [9]:
x = X_train['FullDescription'].str.lower()

In [10]:
del X_train['FullDescription']

In [19]:
X_train

LocationNormalized ContractTime  SalaryNormalized  \
0                London    permanent             33000   
1                London    permanent             50000   
2     South East London    permanent             40000   
3               Dereham    permanent             22500   
4      Sutton Coldfield          nan             20355   
...                 ...          ...               ...   
9995    Nottinghamshire    permanent             30000   
9996             London    permanent             34091   
9997                 UK    permanent             37500   
9998       Warwickshire    permanent             38500   
9999   Isle Of Anglesey    permanent             12096   

                                        FullDescription  
0     international sales manager london     k      ...  
1     an ideal opportunity for an individual that ha...  
2     online content and brand manager   luxury reta...  
3     a great local marketleader is seeking a perman...  
4     registered nurse   rgn  nursing home for young...  
...                                                 ...  
9995  structural design experience in abundance and ...  
9996  the uk s leading independent think tank on int...  
9997  java  developer  web development  web services...  
9998  we are currently looking for a strong business...  
9999  ymddiriedolaeth genedlaethol national trust p ...  

[10000 rows x 4 columns]

In [12]:
X_train['FullDescription'] = pd.Series(x, index=X_train.index)

In [13]:
X_train.head(3)

LocationNormalized ContractTime  SalaryNormalized  \
0             London    permanent             33000   
1             London    permanent             50000   
2  South East London    permanent             40000   

                                     FullDescription  
0  international sales manager london ****k  ****...  
1  an ideal opportunity for an individual that ha...  
2  online content and brand manager// luxury reta...

In [14]:
X_train['FullDescription'] = X_train['FullDescription'].replace('[^a-zA-Z0-9]', ' ', regex = True)

In [15]:
X_train.head(3)

LocationNormalized ContractTime  SalaryNormalized  \
0             London    permanent             33000   
1             London    permanent             50000   
2  South East London    permanent             40000   

                                     FullDescription  
0  international sales manager london     k      ...  
1  an ideal opportunity for an individual that ha...  
2  online content and brand manager   luxury reta...

In [153]:
#vectorizer = TfidfVectorizer(min_df=5)
#X_train['FullDescription'] = vectorizer.fit_transform(X_train['FullDescription'])

In [16]:
X_train['LocationNormalized'].fillna('nan', inplace=True)
X_train['ContractTime'].fillna('nan', inplace=True)

In [17]:
from sklearn.feature_extraction import DictVectorizer
enc = DictVectorizer()
X_train_categ = enc.fit_transform(X_train[['LocationNormalized', 'ContractTime']].to_dict('records'))

In [18]:
vectorizer=TfidfVectorizer(input='content', encoding='utf-8', 
decode_error='strict', strip_accents=None, lowercase=True, 
preprocessor=None, tokenizer=None, analyzer='word', 
stop_words=None, min_df=5)
X_tr=vectorizer.fit_transform(X_train['FullDescription'])

In [20]:
X_train_categ

<10000x903 sparse matrix of type '<class 'numpy.float64'>'
	with 20000 stored elements in Compressed Sparse Row format>

In [21]:
X_tr

<10000x10092 sparse matrix of type '<class 'numpy.float64'>'
	with 1372558 stored elements in Compressed Sparse Row format>

In [22]:
from scipy.sparse import hstack

In [23]:
h = hstack([X_tr, X_train_categ])

In [24]:
h

<10000x10995 sparse matrix of type '<class 'numpy.float64'>'
	with 1392558 stored elements in COOrdinate format>

In [25]:
y_train = X_train['SalaryNormalized']

In [26]:
from sklearn.linear_model import Ridge

In [27]:
clf = Ridge(alpha=1.0, random_state=241)
clf.fit(h, y_train) 

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=241, solver='auto', tol=0.001)

In [28]:
X_test = pd.read_csv('salary-test-mini.csv')

In [29]:
X_test_1= X_test.head(1)

In [30]:
X_test_1

FullDescription LocationNormalized  \
0  We currently have a vacancy for an HR Project ...      Milton Keynes   

  ContractTime  SalaryNormalized  
0     contract               NaN

In [31]:
X_test_2 = X_test.tail(1)

In [32]:
X_test_2

FullDescription LocationNormalized  \
1  A Web developer opportunity has arisen with an...         Manchester   

  ContractTime  SalaryNormalized  
1    permanent               NaN

In [33]:
x = X_test_1['FullDescription'].str.lower()
del X_test['FullDescription']
X_test_1['FullDescription'] = pd.Series(x, index=X_test_1.index)

C:\FolderForAnaconda\envs\ipykernel_py3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [34]:
X_test_1

FullDescription LocationNormalized  \
0  we currently have a vacancy for an hr project ...      Milton Keynes   

  ContractTime  SalaryNormalized  
0     contract               NaN

In [35]:
X_test_1['FullDescription'] = X_test_1['FullDescription'].replace('[^a-zA-Z0-9]', ' ', regex = True)

C:\FolderForAnaconda\envs\ipykernel_py3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [36]:
X_test_1['LocationNormalized'].fillna('nan', inplace=True)
X_test_1['ContractTime'].fillna('nan', inplace=True)

C:\FolderForAnaconda\envs\ipykernel_py3\lib\site-packages\pandas\core\generic.py:6287: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


In [37]:
X_test_1_categ = enc.transform(X_test_1[['LocationNormalized', 'ContractTime']].to_dict('records'))

In [40]:
X_test_1_categ

<1x903 sparse matrix of type '<class 'numpy.float64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [38]:
X_te_1=vectorizer.transform(X_test_1['FullDescription'])

In [39]:
X_te_1

<1x10092 sparse matrix of type '<class 'numpy.float64'>'
	with 172 stored elements in Compressed Sparse Row format>

In [41]:
X_TEST_1 = hstack([X_te_1, X_test_1_categ])

In [42]:
X_TEST_1

<1x10995 sparse matrix of type '<class 'numpy.float64'>'
	with 174 stored elements in COOrdinate format>

In [175]:
clf.predict(X_TEST_1)

array([53614.65259174])

In [176]:
X_test_2

FullDescription LocationNormalized  \
1  A Web developer opportunity has arisen with an...         Manchester   

  ContractTime  SalaryNormalized  
1    permanent               NaN

In [177]:
x = X_test_2['FullDescription'].str.lower()
X_test_2['FullDescription'] = pd.Series(x, index=X_test_2.index)
X_test_2['FullDescription'] = X_test_2['FullDescription'].replace('[^a-zA-Z0-9]', ' ', regex = True)

C:\Elizaveta\AnacPhyton\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Elizaveta\AnacPhyton\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [178]:
X_test_2

FullDescription LocationNormalized  \
1  a web developer opportunity has arisen with an...         Manchester   

  ContractTime  SalaryNormalized  
1    permanent               NaN

In [179]:
X_test_2_categ = enc.transform(X_test_2[['LocationNormalized', 'ContractTime']].to_dict('records'))
X_te_2=vectorizer.transform(X_test_2['FullDescription'])

In [180]:
X_TEST_2 = hstack([X_te_2, X_test_2_categ])

In [182]:
clf.predict(X_TEST_2)

array([36298.48370262])

# PCA

-работать с методом главных компонент
-использовать его для вычисления улучшенного индекса Доу-Джонса

В этом задании понадобится измерять схожесть двух наборов величин. Если имеется набор пар измерений (например, одна пара — предсказания двух классификаторов для одного и того же объекта), то охарактеризовать их зависимость друг от друга можно с помощью корреляции Пирсона. Она принимает значения от -1 до 1 и показывает, насколько данные величины линейно зависимы. Если корреляция равна -1 или 1, то величины линейно выражаются друг через друга. Если она равна нулю, то линейная зависимость между величинами отсутствует.

In [198]:
from sklearn.decomposition import PCA
import numpy as np

In [183]:
data = pd.read_csv('close_prices.csv')

In [185]:
data.head(3)

date        AXP          BA        CAT       CSCO         CVX  \
0  2013-09-23  76.440002  117.510002  85.029999  24.270000  125.519997   
1  2013-09-24  76.070000  119.000000  85.110001  24.139999  124.489998   
2  2013-09-25  75.989998  118.510002  84.500000  24.430000  124.070000   

          DD        DIS         GE          GS    ...            PFE  \
0  59.409999  64.750000  24.280001  165.250000    ...      28.799999   
1  59.319997  64.320000  24.320000  162.970001    ...      28.709999   
2  59.319997  64.449997  24.230000  162.309998    ...      28.490000   

          PG          T        TRV        UNH         UTX           V  \
0  79.279999  34.220001  86.379997  71.820000  109.419998  196.240005   
1  78.620003  34.090000  85.870003  72.320000  110.000000  193.339996   
2  77.720001  34.049999  85.980003  71.980003  109.260002  191.559998   

          VZ        WMT        XOM  
0  47.980000  76.419998  87.750000  
1  47.270000  75.750000  87.360001  
2  46.950001  74.650002  87.139999  

[3 rows x 31 columns]

In [187]:
pca = PCA(n_components=10)

In [189]:
data=data[data.columns[1:]]

In [194]:
pca.fit(data)

PCA(copy=True, iterated_power='auto', n_components=10, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [197]:
print (pca.explained_variance_ratio_)

[0.73897118 0.11007169 0.04995088 0.0287492  0.02215448 0.01931577
 0.00674853 0.00614091 0.00320594 0.00305611]


In [207]:
for n in range (0,10):
    if (np.sum(pca.explained_variance_ratio_[0:n])>=0.9):
        print n
        break

4


In [209]:
arr = pca.transform(data)

In [218]:
features_first_comp=[]
for i in range(len(data)):
    features_first_comp.append(arr[i][0])

In [234]:
ind = pd.read_csv('djia_index.csv')
ind

date           DJI
0    2013-09-23  15401.379883
1    2013-09-24  15334.589844
2    2013-09-25  15273.259766
3    2013-09-26  15328.299805
4    2013-09-27  15258.240234
5    2013-09-30  15129.669922
6    2013-10-01  15191.700195
7    2013-10-02  15133.139648
8    2013-10-03  14996.480469
9    2013-10-04  15072.580078
10   2013-10-07  14936.240234
11   2013-10-08  14776.530273
12   2013-10-09  14802.980469
13   2013-10-10  15126.070312
14   2013-10-11  15237.110352
15   2013-10-14  15301.259766
16   2013-10-15  15168.009766
17   2013-10-16  15373.830078
18   2013-10-17  15371.650391
19   2013-10-18  15399.650391
20   2013-10-21  15392.200195
21   2013-10-22  15467.660156
22   2013-10-23  15413.330078
23   2013-10-24  15509.209961
24   2013-10-25  15570.280273
25   2013-10-28  15568.929688
26   2013-10-29  15680.349609
27   2013-10-30  15618.759766
28   2013-10-31  15545.750000
29   2013-11-01  15615.549805
..          ...           ...
344  2015-02-04  17673.019531
345  2015-02-05  17884.880859
346  2015-02-06  17824.289062
347  2015-02-09  17729.210938
348  2015-02-10  17868.759766
349  2015-02-11  17862.140625
350  2015-02-12  17972.380859
351  2015-02-13  18019.349609
352  2015-02-17  18047.580078
353  2015-02-18  18029.849609
354  2015-02-19  17985.769531
355  2015-02-20  18140.439453
356  2015-02-23  18116.839844
357  2015-02-24  18209.189453
358  2015-02-25  18224.570312
359  2015-02-26  18214.419922
360  2015-02-27  18132.699219
361  2015-03-02  18288.630859
362  2015-03-03  18203.369141
363  2015-03-04  18096.900391
364  2015-03-05  18135.720703
365  2015-03-06  17856.779297
366  2015-03-09  17995.720703
367  2015-03-10  17662.939453
368  2015-03-11  17635.390625
369  2015-03-12  17895.220703
370  2015-03-13  17749.310547
371  2015-03-16  17977.419922
372  2015-03-17  17849.080078
373  2015-03-18  18076.189453

[374 rows x 2 columns]

In [236]:
ind=ind['DJI']

In [238]:
ind = ind.as_matrix(columns=None)

In [240]:
np.corrcoef(features_first_comp, ind)

array([[1.        , 0.90965222],
       [0.90965222, 1.        ]])

In [256]:
index=0
max_ = pca.components_[0][0]
for i in range (1, 30):
    if(max_<pca.components_[0][i]):
        max_=pca.components_[0][i]
        index=i
print index+1

27


In [255]:
index

28

In [247]:
pca.components_[0]

array([ 1.61383840e-02,  1.20644923e-01, -5.16612711e-02,  5.04842369e-02,
       -1.25859933e-01,  1.14089567e-01,  2.33906290e-01, -6.20513749e-03,
        2.51227032e-01,  2.88996029e-01, -2.64998795e-01,  9.31320168e-02,
        9.13948403e-02,  4.69879340e-02,  2.90549417e-02, -2.61068828e-02,
        3.29615584e-01,  7.13897133e-02,  7.62295699e-02,  2.11888868e-01,
        2.30922941e-02,  7.77316954e-02, -7.20594590e-03,  1.89479745e-01,
        3.21564017e-01,  5.36834873e-02,  5.79683946e-01,  1.09122230e-04,
        8.71614334e-02, -4.29421420e-02])